# Generated by Django 3.2.5 on 2021-12-24 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecgsproject.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_utilisateur', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('prenom', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('tel', models.CharField(max_length=20)),
                ('entreprise', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'ecgsproject_customuser',
            },
            managers=[
                ('objects', ecgsproject.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id_resultat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nb_h_tot_prest_ann', models.PositiveIntegerField(blank=True, null=True)),
                ('utilisation_inutile', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('tva_cli', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('adr_entreprise', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('ecgsproject.customuser',),
            managers=[
                ('objects', ecgsproject.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Integrateur',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('tva_integrateur', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('adr_entreprise', models.CharField(max_length=254)),
                ('lieu_fonction', models.CharField(max_length=254)),
                ('tel_contact', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('ecgsproject.customuser',),
            managers=[
                ('objects', ecgsproject.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ecgsproject.client')),
                ('num_contrat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_creation', models.DateField()),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('commentaires_contrat', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ecgsproject.client',),
            managers=[
                ('objects', ecgsproject.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_employe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lieu_fonction', models.CharField(max_length=254)),
                ('id_integrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.integrateur')),
            ],
            options={
                'abstract': False,
            },
            bases=('ecgsproject.customuser',),
            managers=[
                ('objects', ecgsproject.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.employe'),
        ),
        migrations.CreateModel(
            name='Contrat_detail',
            fields=[
                ('contrat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecgsproject.contrat')),
                ('statut', models.CharField(choices=[('Signé', 'Signé'), ('En Attente', 'En Attente')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('ecgsproject.contrat',),
            managers=[
                ('objects', ecgsproject.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('contrat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ecgsproject.contrat')),
                ('num_licence', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_achat', models.DateField()),
                ('nombre', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=250)),
                ('commentaires_lic', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ecgsproject.contrat',),
            managers=[
                ('objects', ecgsproject.models.UserManager()),
            ],
        ),
    ]
