# Generated by Django 3.2.5 on 2021-09-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='createur',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.customuser'),
            preserve_default=False,
        ),
    ]
