# Generated by Django 3.2.5 on 2021-12-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resultat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.resultat'),
        ),
    ]
