# Generated by Django 3.2.5 on 2021-12-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.customuser'),
        ),
    ]
