# Generated by Django 3.2.5 on 2022-01-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0002_auto_20220108_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='client',
            name='adr_entreprise',
            field=models.CharField(max_length=254, verbose_name="adresse de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.CharField(editable=False, max_length=254, verbose_name='créé par'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tva_cli',
            field=models.CharField(max_length=14, verbose_name='tva'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='created_by',
            field=models.CharField(editable=False, max_length=254, verbose_name='créé par'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='num_contrat',
            field=models.CharField(max_length=254, unique=True, verbose_name='numéro du contrat'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_by',
            field=models.CharField(editable=False, max_length=254, verbose_name='créé par'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='resultat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.resultat', verbose_name='résultat'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='created_by',
            field=models.CharField(editable=False, max_length=254, verbose_name='créé par'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='lieu_fonction',
            field=models.CharField(max_length=254, verbose_name='lieu de sa fonction'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='adr_entreprise',
            field=models.CharField(max_length=254, verbose_name="adresse de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='created_by',
            field=models.CharField(editable=False, max_length=254, verbose_name='créé par'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='lieu_fonction',
            field=models.CharField(max_length=254, verbose_name='lieu de sa fonction'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='tel_contact',
            field=models.CharField(max_length=20, verbose_name='téléphone de contact'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='tva_integrateur',
            field=models.CharField(max_length=14, verbose_name='tva'),
        ),
    ]
