# Generated by Django 3.2.5 on 2021-08-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0003_client_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='author',
        ),
    ]
