# Generated by Django 3.2.5 on 2022-01-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0003_auto_20220108_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='commentaires_contrat',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='commentaires'),
        ),
        migrations.AlterField(
            model_name='contrat_detail',
            name='date_signature',
            field=models.DateField(blank=True, null=True, verbose_name='date de signature'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='commentaires_lic',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='commentaires'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='date_achat',
            field=models.DateField(verbose_name="date d'achat de licence"),
        ),
        migrations.AlterField(
            model_name='licence',
            name='nombre',
            field=models.PositiveIntegerField(verbose_name='nombre de licences'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='num_licence',
            field=models.CharField(max_length=254, unique=True, verbose_name='numéro licence'),
        ),
    ]
