# Generated by Django 3.2.5 on 2021-12-30 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0005_auto_20211229_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='contrat_detail',
        ),
        migrations.RemoveField(
            model_name='contrat_detail',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='contrat_detail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contrat_detail',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='contrat_detail',
            name='contrat_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ecgsproject.contrat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat_detail',
            name='id_contrat_detail',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
