# Generated by Django 3.2.5 on 2021-08-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0005_integrateur_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='integrateur',
            name='author',
        ),
    ]
