# Generated by Django 3.2.5 on 2022-01-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0005_alter_resultat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat_detail',
            name='date_signature',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='contrat_detail',
            name='statut',
            field=models.CharField(choices=[('Proposition', 'Proposition'), ('En négociation', 'En négociation'), ('Signé', 'Signé'), ('Arrêté', 'Arrêté')], max_length=200),
        ),
    ]
