# Generated by Django 3.2.5 on 2021-12-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0006_auto_20211230_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='date_signature',
        ),
        migrations.AddField(
            model_name='contrat_detail',
            name='date_signature',
            field=models.DateField(blank=True, null=True),
        ),
    ]
