# Generated by Django 3.2.5 on 2022-01-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0006_auto_20220113_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modifié le'),
        ),
    ]
