# Generated by Django 3.2.5 on 2021-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0006_auto_20210818_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('Interessé', 'Interessé'), ('Abonné', 'Abonné')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
