# Generated by Django 3.2.5 on 2021-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0007_client_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='mail',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
