# Generated by Django 3.2.5 on 2022-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0007_auto_20220113_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(editable=False, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='created_date',
            field=models.DateTimeField(editable=False, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_date',
            field=models.DateTimeField(editable=False, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='created_date',
            field=models.DateTimeField(editable=False, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='created_date',
            field=models.DateTimeField(editable=False, verbose_name='créé le'),
        ),
    ]
