# Generated by Django 3.2.5 on 2021-12-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0007_auto_20211230_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
    ]
