# Generated by Django 3.2.5 on 2022-01-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0008_auto_20220113_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='resultat',
        ),
        migrations.AddField(
            model_name='resultat',
            name='utilisateur',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
