# Generated by Django 3.2.5 on 2021-12-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0008_alter_contrat_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='num_contrat',
            new_name='id_contrat',
        ),
    ]
