# Generated by Django 3.2.5 on 2021-08-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0009_integrateur_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrateur',
            name='author',
        ),
    ]
