# Generated by Django 3.2.5 on 2021-12-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0009_rename_num_contrat_contrat_id_contrat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licence',
            old_name='num_licence',
            new_name='id_licence',
        ),
    ]
