# Generated by Django 3.2.5 on 2022-01-14 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0009_auto_20220113_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator()], verbose_name='téléphone'),
        ),
    ]
