# Generated by Django 3.2.5 on 2022-01-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0010_alter_customuser_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='créé le'),
        ),
    ]
