# Generated by Django 3.2.5 on 2021-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0010_rename_num_licence_licence_id_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='num_licence',
            field=models.CharField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
