# Generated by Django 3.2.5 on 2021-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0011_licence_num_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='num_contrat',
            field=models.CharField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
