# Generated by Django 3.2.5 on 2021-12-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0013_auto_20211230_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='contrat_detail',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='contrat_detail',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='integrateur',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='integrateur',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
