# Generated by Django 3.2.5 on 2021-08-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0013_auto_20210820_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='author',
            new_name='createur',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='author',
            new_name='createur',
        ),
        migrations.RenameField(
            model_name='personne',
            old_name='author',
            new_name='createur',
        ),
    ]
