# Generated by Django 3.2.5 on 2022-01-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0014_auto_20220120_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat_detail',
            name='contrat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecgsproject.contrat'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecgsproject.contrat'),
        ),
    ]
