# Generated by Django 3.2.5 on 2022-01-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0015_auto_20220101_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='modified_by',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='created_by',
            field=models.CharField(default=3, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='modified_by',
            field=models.CharField(default=4, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='created_by',
            field=models.CharField(default=5, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='modified_by',
            field=models.CharField(default=6, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='integrateur',
            name='created_by',
            field=models.CharField(default=7, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrateur',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='integrateur',
            name='modified_by',
            field=models.CharField(default=8, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrateur',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
