# Generated by Django 3.2.5 on 2022-01-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0017_auto_20220120_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecgsproject.employe'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecgsproject.client'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='tva_integrateur',
            field=models.CharField(max_length=14, unique=True, verbose_name='tva'),
        ),
    ]
