# Generated by Django 3.2.5 on 2022-01-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0018_auto_20220120_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.employe'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecgsproject.client'),
        ),
    ]
