# Generated by Django 3.2.5 on 2022-01-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0020_auto_20220120_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecgsproject.client'),
        ),
    ]
