# Generated by Django 3.2.5 on 2022-01-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0021_alter_contrat_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Anonyme'), to='ecgsproject.client'),
        ),
    ]
