# Generated by Django 3.2.5 on 2022-01-21 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0024_alter_contrat_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='periode_val',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='période de validité'),
            preserve_default=False,
        ),
    ]
