# Generated by Django 3.2.5 on 2022-01-21 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0025_licence_periode_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='nb_h_tot_prest_ann',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='result',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='utilisation_inutile',
        ),
        migrations.AddField(
            model_name='resultat',
            name='nb_appareils',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='nb_conges',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='prix_kwh',
            field=models.FloatField(blank=True, default=0.25, editable=False),
        ),
        migrations.AddField(
            model_name='resultat',
            name='result_euro',
            field=models.FloatField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultat',
            name='result_pourcent',
            field=models.FloatField(blank=True, default=0.0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultat',
            name='type_compteur',
            field=models.CharField(choices=[('Mono-horaire', 'Mono-horaire'), ('Bi-horaire', 'Bi-horaire')], default=django.utils.timezone.now, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
