# Generated by Django 3.2.5 on 2022-01-23 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0027_auto_20220122_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='integrateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecgsproject.integrateur'),
        ),
    ]
