# Generated by Django 3.2.5 on 2022-01-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0028_alter_employe_integrateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecgsproject.customuser'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecgsproject.client'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='integrateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.integrateur'),
            preserve_default=False,
        ),
    ]
