# Generated by Django 3.2.5 on 2022-01-24 18:47

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0029_auto_20220123_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, validators=[django.core.validators.RegexValidator()], verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='integrateur',
            name='tel_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='téléphone de contact'),
        ),
    ]
