# Generated by Django 3.2.5 on 2022-01-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0032_auto_20220126_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Resultat',
        ),
    ]
