# Generated by Django 3.2.5 on 2022-01-27 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0033_auto_20220127_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id_resultat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nb_appareils', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('type_compteur', models.CharField(choices=[('Mono-horaire', 'Mono-horaire'), ('Bi-horaire', 'Bi-horaire')], editable=False, max_length=50)),
                ('result_pourcent', models.FloatField(blank=True, editable=False)),
                ('result_wh', models.FloatField(blank=True, editable=False)),
                ('result_euro', models.FloatField(blank=True, editable=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecgsproject.customuser')),
            ],
        ),
    ]
