# Generated by Django 3.2.5 on 2022-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsproject', '0034_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='a_contacter',
            field=models.BooleanField(default=False),
        ),
    ]
